network:
    version: 2
    ethernets:
        eno1:
            addresses:
                - 192.168.178.10/24
            nameservers:
                addresses: [8.8.8.8, 8.8.4.4]
            routes:
                - to: default
                  via: 192.168.178.1