version: "3.2"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - homeserver
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${password}
    volumes:
      - /_store/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    networks:
      - homeserver
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${password}
    ports:
      - "5050:80"
  fakesmtp:
    container_name: fakesmtp
    image: gessnerfl/fake-smtp-server
    restart: always
    networks:
      - homeserver
    environment:
      fakesmtp.authentication.username: admin@admin.com
      fakesmtp.authentication.password:fakemail: ${password}
    ports:
      - "5080:5080"
      - "5025:5025"
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    restart: unless-stopped
    networks:
      - homeserver
    volumes:
      - /_store/verdaccio/storage:/verdaccio/storage
      - /_store/verdaccio/plugins:/verdaccio/plugins
    ports:
      - "4873:4873"
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    volumes:
      - /_store/portainer/etc/localtime:/etc/localtime:ro
      - /_store/portainer/var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9000:9000
networks:
  homeserver:
    driver: bridge
